# Slurm bwuni cpu
name: "SLURM"   # MUST BE "SLURM"
partition: "single"  # "single" for cpu, "gpu_4" or gpu_8" for gpu
job-name: "test"# this will be the experiment's name in slurm
num_parallel_jobs: 6 # max number of jobs executed in parallel
ntasks: 1   #  leave that like it is
cpus-per-task: 1   # there are 10 cores for each GPU
time: 1000   # in minutes
mem-per-cpu: 64 # Optional - Cluster specific
slurm_log: "./slurmlog/"            # optional. dir in which slurm output and error logs will be saved. Defaults to EXPERIMENTCONFIG.path


---
# DEFAULT parameters (Optional)
name: "DEFAULT"   # MUST BE DEFAULT

# Implementation default parameters
path: "./output/"   # location to save results in
repetitions: 1  # number of times one set of parameters is run

params:
  # this is where you specify all parameters needed for your experiment.
  # the tree structure you define here will be translated to a nested python dictionary
  action_space_type: 'discrete'
  env_name: 'acrobot'
  algo_name: 'sac'
  n_actions: 2500
  pre_steps: 100
  layers: [256, 256]
  lr: 0.003

---
name: "rlv"
path: "./output/"
repetitions: 1   # repeat 8 times

params:
  action_space_type: 'discrete'
  env_name: 'acrobot'
  algo_name: 'sac'
  n_games: 5000
  pre_steps: 100
  layers: [256, 256]
  lr: 0.003