# Slurm bwuni cpu
name: "SLURM"   # MUST BE "SLURM"
partition: 'dev_multiple_e'
job-name: "sac_rlv"# this will be the experiment's name in slurm
num_parallel_jobs: 1 # max number of jobs executed in parallel
mem: 10000
nodes: 8
ntasks-per-node: 28
time: 30   # in minutes

---
# DEFAULT parameters (Optional)
name: "DEFAULT"   # MUST BE DEFAULT

# Implementation default parameters
path: "./output/"   # location to save results in
repetitions: 1   # number of times one set of parameters is run

params:
  # this is where you specify all parameters needed for your experiment.
  # the tree structure you define here will be translated to a nested python dictionary
  action_space_type: 'discrete'
  env_name: 'acrobot'
  algo_name: 'sac'
  n_actions: 2500
  pre_steps: 100
  layer1_size: 256
  layer2_size: 256
  lr: 0.003

---
name: "rlv"
path: "./output/"
repetitions: 1   # repeat 8 times

params:
  action_space_type: 'discrete'
  env_name: 'acrobot'
  algo_name: 'rlv'
  n_games: 5000
  pre_steps: 100
  layer1_size: 256
  layer2_size: 256
  lr: 0.003