---
name: "SLURM"   # MUST BE "SLURM"
# Required
partition: "single"
job-name: "RLV"    # this will be the experiments name in slurm
num_parallel_jobs: 1
ntasks: 1
cpus-per-task: 4
mem-per-cpu: 16000
time: 6000 # in minutes
sbatch_args: # Dictionary of SBATCH keywords and arguments
  distribution: cyclic  # To have repetitions of the same exp be distributed to different nodes
slurm_log: "./slurmlog/"


---
# DEFAULT parameters (Optional)
name: "DEFAULT"   #  useful for paralellization. defaults to 1.
reps_in_parallel: 1 # number of repetitions in each job that are executed in parallel. defaults to 1.
reps_per_job: 1 # number of repetitions in each job.
repetitions: 1  # number of times one set of parameters is run

params:
  # this is where you specify all parameters needed for your experiment.MUST BE DEFAULT
  #path: "../output/rlv"   # location to save results in
  env_name: 'acrobot_continuous'
  algo_name: 'sac'
  policy: 'MlpPolicy'
  lr_inverse_model: 0.0003
  wandb_log: True
  lr_sac: 0.003
  buffer_size: 1000000
  learning_starts: 1000
  batch_size: 256
  tau: 0.005
  acrobot_human_data: True
  train_sac: False
  gamma: 0.99
  train_freq: 1
  gradient_steps: 1
  total_steps: 3000
  project_name: 'unknown_project'
  run_name: 'test'
  log_dir: '../output/tmp/gym/'

---
name: "sac"
path: "../output/rlv/"
repetitions: 2   # repeat 8 times

# Experiment Parameters
params:
  total_steps: 1000000
  project_name: 'acrobot_sac'
  run_name: 'one_million_steps_acrobot'
  env_name: "acrobot_continuous"
  algo_name: 'sac'
  policy: 'MlpPolicy'

---
name: "sac"
path: "../output/rlv/"
repetitions: 2   # repeat 8 times

# Experiment Parameters
params:
  total_steps: 1000000
  project_name: 'visual_pusher_sac'
  run_name: 'one_million_steps_pusher'
  env_name: "visual_pusher"
  algo_name: 'sac'
  policy: 'MlpPolicy'




