---
name: "SLURM"   # MUST BE "SLURM"
# Required
partition: "fat"
job-name: "SAC"    # this will be the experiments name in slurm
num_parallel_jobs: 1
ntasks: 1
cpus-per-task: 4
mem-per-cpu: 16000
time: 1200 # in minutes
slurm_log: "../output/slurmlog/"


---
# DEFAULT parameters (Optional)
name: "DEFAULT"   #  useful for paralellization. defaults to 1.
reps_in_parallel: 1 # number of repetitions in each job that are executed in parallel. defaults to 1.
reps_per_job: 1 # number of repetitions in each job.
repetitions: 1  # number of times one set of parameters is run

params:
  # this is where you specify all parameters needed for your experiment.MUST BE DEFAULT
  path: "../output/sac"   # location to save results in
  env_name: 'acrobot_continuous'
  algo_name: 'sac'
  wandb_log: False
  policy: 'MlpPolicy'
  gamma: 0.99
  train_freq: 1
  gradient_steps: 1
  total_steps: 1000000
  project_name: 'unknown_project'
  run_name: 'test'
  lr_sac: 0.0003
  buffer_size: 1000000
  learning_starts: 1000
  batch_size: 256
  tau: 0.005
  lr_inverse_model: 0.0003
  acrobot_paper_data: False
  log_dir: '../output/saved_models'

---

name: "visual_pusher"
path: "../output/sac/"
repetitions: 1   # repeat 8 times

# Experiment Parameters
params:
  total_steps: 1000000
  project_name: 'sac'
  run_name: 'sac'
  env_name: "visual_pusher"
  algo_name: 'sac'
  policy: 'MlpPolicy'

